### ISSUE TITLE
What about requiring multiple css?

### ISSUE THREAD

**Issue by drpicox** [ByteMuse/cssnextify#3]
Given the next case:

``` javascript
// ./app.js
require('./app.css');

var component = require('component');
// do something with component
```

``` javascript
// component/index.js
require('./component.css');

module.exports = // define something
```

``` css
/* ./app.css */
:root {
  --componentColor: red;
}
```

``` css
/* component/component.css */
component {
  display: block;
  background-color: var(--componentColor);
}
```

It does not behaves as expected, `./app.css` and `component/component.css` are processed separately and variable value is never applied to the component.

Any chance to process all css files together in the same bundle?
